tap "azure/kubelogin", "https://github.com/Azure/homebrew-kubelogin"
tap "hashicorp/tap"
tap "terraform-linters/tap"
# Simple, modern, secure file encryption
brew "age"
# Microsoft Azure CLI 2.0
brew "azure-cli"
# Manage your dotfiles across multiple diverse machines, securely
brew "chezmoi"
# Load/unload environment variables based on $PWD
brew "direnv"
# Command-line fuzzy finder written in Go
brew "fzf"
# Distributed revision control system
brew "git"
# Highly customizable changelog generator
brew "git-cliff"
# Kubernetes CLI To Manage Your Clusters In Style!
brew "k9s"
# Mac App Store command-line interface
brew "mas"
# Port scanning utility for large networks
brew "nmap"
# Drop-in replacement for Terraform. Infrastructure as Code Tool
brew "opentofu"
# Framework for managing multi-language pre-commit hooks
brew "pre-commit"
# Fast Git hook manager written in Rust, drop-in alternative to pre-commit
brew "prek"
# Shell extension to navigate your filesystem faster
brew "zoxide"
# Password manager that keeps all passwords secure behind one password
cask "1password"
# Enable Windows-like alt-tab
cask "alt-tab"
# Display management tool
cask "betterdisplay"
# Web browser focusing on privacy
cask "brave-browser"
# Open source IDE for exploring and testing APIs
cask "bruno"
# Developer platform
cask "dotnet-sdk"
# Developer platform
cask "dotnet-sdk@8"
# Developer platform
cask "dotnet-sdk@9"
# Web browser
cask "firefox"
# Terminal emulator as alternative to Apple's Terminal app
cask "iterm2"
# Explorer for Azure Storage
cask "microsoft-azure-storage-explorer"
# Pluggable Terraform linter
cask "terraform-linters/tap/tflint"
# Open-source code editor
cask "visual-studio-code"
# Connect to Windows
cask "windows-app"
mas "WireGuard", id: 1451685025
vscode "github.copilot-chat"
vscode "ms-vscode-remote.remote-ssh"
vscode "ms-vscode-remote.remote-ssh-edit"
vscode "ms-vscode.remote-explorer"
npm "@angular/cli"
npm "corepack"
